"""Path-addable HYCOM OBC connector package for FVCOM workflows."""

from __future__ import annotations

from .hycom_fetcher import (
    DEFAULT_LAT_RANGE,
    DEFAULT_LON_RANGE,
    HYCOM_2D_VARIABLES,
    HYCOM_3D_VARIABLES,
    HYCOM_PRODUCT_VARIABLES,
    HYCOM_VARIABLE_ALIASES,
    HYCOM_Z_LEVELS,
    HycomDownloadError,
    HycomDownloadRequest,
    NotebookProgressDisplay,
    fetch_hycom,
    fetch_hycom_points,
    fetch_hycom_ssh_month,
    fetch_hycom_ts_month,
    get_experiment_for_date,
    interp_ssh_to_obc,
    interp_ts_to_obc,
    load_ssh_checkpoints,
    load_ts_checkpoints,
    plan_hycom_chunks,
    remap_hycom_z_to_sigma,
    resample_to_fvcom_time,
    save_ssh_checkpoint,
    save_ts_checkpoint,
)
from .grid_utils import datetime64_to_mjd, mjd_to_datetime64

__all__ = [
    "DEFAULT_LAT_RANGE",
    "DEFAULT_LON_RANGE",
    "HYCOM_2D_VARIABLES",
    "HYCOM_3D_VARIABLES",
    "HYCOM_PRODUCT_VARIABLES",
    "HYCOM_VARIABLE_ALIASES",
    "HYCOM_Z_LEVELS",
    "HycomDownloadError",
    "HycomDownloadRequest",
    "NotebookProgressDisplay",
    "datetime64_to_mjd",
    "fetch_hycom",
    "fetch_hycom_points",
    "fetch_hycom_ssh_month",
    "fetch_hycom_ts_month",
    "get_experiment_for_date",
    "interp_ssh_to_obc",
    "interp_ts_to_obc",
    "load_ssh_checkpoints",
    "load_ts_checkpoints",
    "mjd_to_datetime64",
    "plan_hycom_chunks",
    "remap_hycom_z_to_sigma",
    "resample_to_fvcom_time",
    "save_ssh_checkpoint",
    "save_ts_checkpoint",
]
