"""Public CFSv2 fetcher API."""

from .cfsv2_fetcher import (
    CFSV2_PRESSURE_BASE_HPA,
    SUBDATASET_ALIASES,
    SUBDATASET_VARIABLES,
    build_cfsv2_plan,
    cfsv2_airprs_to_absolute_pa,
    fetch_cfsv2_plan,
    fetch_cfsv2_window,
    fetch_cfsv2_year,
    fetch_pressure_year,
    fetch_wind_year,
    health_cfsv2,
    inventory_cfsv2,
    load_and_concat_years,
    normalize_subdataset,
    validate_plan,
)
from .cfs_grib_core import (
    PRODUCTS,
    build_plan as build_atmospheric_plan,
    execute_request as execute_atmospheric_request,
    fetch_plan as fetch_atmospheric_plan,
    health as health_atmospheric,
    normalize_request as normalize_atmospheric_request,
    runtime_preflight,
)

__all__ = [
    "CFSV2_PRESSURE_BASE_HPA",
    "SUBDATASET_ALIASES",
    "SUBDATASET_VARIABLES",
    "build_cfsv2_plan",
    "cfsv2_airprs_to_absolute_pa",
    "fetch_cfsv2_plan",
    "fetch_cfsv2_window",
    "fetch_cfsv2_year",
    "fetch_pressure_year",
    "fetch_wind_year",
    "health_cfsv2",
    "inventory_cfsv2",
    "load_and_concat_years",
    "normalize_subdataset",
    "validate_plan",
    "PRODUCTS",
    "build_atmospheric_plan",
    "execute_atmospheric_request",
    "fetch_atmospheric_plan",
    "health_atmospheric",
    "normalize_atmospheric_request",
    "runtime_preflight",
]
